# Generated by Django 2.2.26 on 2023-10-20 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0017_auto_20231020_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforecastmonth',
            name='mean_abs_error',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='postforecastmonth',
            name='model_loss',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 757006)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 757006)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 757006)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 758006)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 758006)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 756005)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 754005)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 755006)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 755006)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 9, 35, 37, 756005)),
        ),
    ]
