# Generated by Django 2.2.26 on 2023-10-24 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0021_auto_20231024_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 550146)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 549132)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 549132)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 551132)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 550146)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 548134)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 546105)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 547118)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 548134)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 27, 49, 549132)),
        ),
    ]
