# Generated by Django 2.2.26 on 2023-11-29 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0022_auto_20231024_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 721961)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 721961)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 720961)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 722960)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 721961)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 719958)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 717963)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 718958)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 719958)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 35, 36, 720961)),
        ),
    ]
