# Generated by Django 3.2.6 on 2024-02-28 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0026_auto_20240222_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostConsistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 787134))),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 790544)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 790544)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 789241)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 792021)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 791472)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 788162)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 787134)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 788162)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 788162)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 16, 12, 27, 789241)),
        ),
    ]
