# Generated by Django 3.2.6 on 2024-03-05 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0032_auto_20240305_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 77949)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 76949)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 76949)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 77949)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 77949)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 76949)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 75028)),
        ),
        migrations.AlterField(
            model_name='postconsistency',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 75952)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 75952)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 75952)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 13, 2, 53, 76949)),
        ),
    ]
