# Generated by Django 3.2.6 on 2024-03-06 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0036_auto_20240305_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 739984)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 738982)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 738982)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 739984)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 739984)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 738982)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 736968)),
        ),
        migrations.AlterField(
            model_name='postconsistency',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 737988)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 737988)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 737988)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 5, 9, 738982)),
        ),
    ]
