# Generated by Django 3.2.6 on 2025-05-28 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_back', '0040_auto_20250528_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='aris',
            name='timestamp_aris',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='flexabilitysim',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='flexi',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='hydro',
            name='timestamp_hydro',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='neykovo',
            name='timestamp_neykovo',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='online',
            name='saved_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 20752)),
        ),
        migrations.AlterField(
            model_name='postconsistency',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 20752)),
        ),
        migrations.AlterField(
            model_name='postforecast',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='postforecastmonth',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
        migrations.AlterField(
            model_name='price',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 13, 9, 39, 21790)),
        ),
    ]
